import turtle
window = turtle.Screen()
window.setup(2000,1800,0,0)
window.bgcolor('skyblue')

 = turtle.Turtle()
.shape('turtle')
.shapesize(3)
.speed(0)
angle = 90
length=100
.penup()
.goto(-400,-300)
.pendown()

.fillcolor('#A51931')
ZENO.begin_fill()
ZENO.begin_fill()
ZENO.forward(length*9)
ZENO.left(angle)
ZENO.forward(length*6)
ZENO.left(angle)
ZENO.forward(length*9)
ZENO.left(angle)
ZENO.forward(length*6)
ZENO.left(angle)
ZENO.end_fill()







turtle.exitonclick()