import turtle

zeno = turtle.Turtle()
screen = turtle.Screen()
screen.setup(2000,1800,0,0)
screen.bgcolor('skyblue')
zeno.shapesize(3)
zeno.speed(0)
zeno.shape('turtle')
angle = 90
length = 100
zeno.penup()
zeno.goto(-400,-300)
zeno.pendown()
window = turtle.Screen()
window.bgcolor('skyblue')

zeno.fillcolor('red')
zeno.begin_fill()
zeno.forward(length*9)
zeno.left(angle)
zeno.forward(length*6)
zeno.left(angle)
zeno.forward(length*9)
zeno.left(angle)
zeno.forward(length*6)
zeno.left(angle)
zeno.penup()


zeno.color('#A51931')
zeno.begin_fill()
zeno.forward(length*9)
zeno.left(angle)
zeno.forward(length*1)
zeno.left(angle)
zeno.forward(length*9)
zeno.left(angle)
zeno.forward(length*1)
zeno.left(angle)
zeno.end_fill()

zeno.right(angle)
zeno.backward(length)
zeno.left(angle)

zeno.color('#F4F5F8')
zeno.begin_fill()
zeno.forward(length*9)
zeno.left(angle)
zeno.forward(length*1)
zeno.left(angle)
zeno.forward(length*9)
zeno.left(angle)
zeno.forward(length*1)
zeno.left(angle)
zeno.end_fill()

zeno.right(angle)
zeno.backward(length)
zeno.left(angle)


zeno.color('#2D2A4A')
zeno.begin_fill()
zeno.forward(length*9)
zeno.left(angle)
zeno.forward(length*1)
zeno.left(angle)
zeno.forward(length*9)
zeno.left(angle)
zeno.forward(length*1)
zeno.left(angle)
zeno.end_fill()

zeno.right(angle)
zeno.backward(length)
zeno.left(angle)

zeno.color('#2D2A4A')
zeno.begin_fill()
zeno.forward(length*9)
zeno.left(angle)
zeno.forward(length*1)
zeno.left(angle)
zeno.forward(length*9)
zeno.left(angle)
zeno.forward(length*1)
zeno.left(angle)
zeno.end_fill()
	
zeno.right(angle)
zeno.backward(length)
zeno.left(angle)

zeno.color('#F4F5F8')
zeno.begin_fill()
zeno.forward(length*9)
zeno.left(angle)
zeno.forward(length*1)
zeno.left(angle)
zeno.forward(length*9)
zeno.left(angle)
zeno.forward(length*1)
zeno.left(angle)
zeno.end_fill()

zeno.right(angle)
zeno.backward(length)
zeno.left(angle)

zeno.color('#A51931')
zeno.begin_fill()
zeno.forward(length*9)
zeno.left(angle)
zeno.forward(length*1)
zeno.left(angle)
zeno.forward(length*9)
zeno.left(angle)
zeno.forward(length*1)
zeno.left(angle)
zeno.end_fill()

zeno.right(angle)
zeno.backward(length)
zeno.left(angle)
zeno.pendown()
zeno.pensize(10)
zeno.right(90)
zeno.pencolor('black')
zeno.pensize(10)
zeno.forward(length*6+100)
zeno.hideturtle()



turtle.exitonclick()