import turtle

CHAPTER = turtle.Turtle()
screen = turtle.Screen()
screen.setup(2000,1800,0,0)
screen.bgcolor('skyblue')
CHAPTER.shapesize(3)
CHAPTER.speed(0)
CHAPTER.shape('turtle')
angle = 90
length = 100
CHAPTER.penup()
CHAPTER.goto(-400,-300)
CHAPTER.pendown()
window = turtle.Screen()
window.bgcolor('skyblue')

CHAPTER.fillcolor('red')
CHAPTER.begin_fill()
CHAPTER.forward(length*9)
CHAPTER.left(angle)
CHAPTER.forward(length*6)
CHAPTER.left(angle)
CHAPTER.forward(length*9)
CHAPTER.left(angle)
CHAPTER.forward(length*6)
CHAPTER.left(angle)
CHAPTER.penup()


CHAPTER.color('#A51931')
CHAPTER.begin_fill()
CHAPTER.forward(length*9)
CHAPTER.left(angle)
CHAPTER.forward(length*1)
CHAPTER.left(angle)
CHAPTER.forward(length*9)
CHAPTER.left(angle)
CHAPTER.forward(length*1)
CHAPTER.left(angle)
CHAPTER.end_fill()

CHAPTER.right(angle)
CHAPTER.backward(length)
CHAPTER.left(angle)

CHAPTER.color('#F4F5F8')
CHAPTER.begin_fill()
CHAPTER.forward(length*9)
CHAPTER.left(angle)
CHAPTER.forward(length*1)
CHAPTER.left(angle)
CHAPTER.forward(length*9)
CHAPTER.left(angle)
CHAPTER.forward(length*1)
CHAPTER.left(angle)
CHAPTER.end_fill()

CHAPTER.right(angle)
CHAPTER.backward(length)
CHAPTER.left(angle)


CHAPTER.color('#2D2A4A')
CHAPTER.begin_fill()
CHAPTER.forward(length*9)
CHAPTER.left(angle)
CHAPTER.forward(length*1)
CHAPTER.left(angle)
CHAPTER.forward(length*9)
CHAPTER.left(angle)
CHAPTER.forward(length*1)
CHAPTER.left(angle)
CHAPTER.end_fill()

CHAPTER.right(angle)
CHAPTER.backward(length)
CHAPTER.left(angle)

CHAPTER.color('#2D2A4A')
CHAPTER.begin_fill()
CHAPTER.forward(length*9)
CHAPTER.left(angle)
CHAPTER.forward(length*1)
CHAPTER.left(angle)
CHAPTER.forward(length*9)
CHAPTER.left(angle)
CHAPTER.forward(length*1)
CHAPTER.left(angle)
CHAPTER.end_fill()
	
CHAPTER.right(angle)
CHAPTER.backward(length)
CHAPTER.left(angle)

CHAPTER.color('#F4F5F8')
CHAPTER.begin_fill()
CHAPTER.forward(length*9)
CHAPTER.left(angle)
CHAPTER.forward(length*1)
CHAPTER.left(angle)
CHAPTER.forward(length*9)
CHAPTER.left(angle)
CHAPTER.forward(length*1)
CHAPTER.left(angle)
CHAPTER.end_fill()

CHAPTER.right(angle)
CHAPTER.backward(length)
CHAPTER.left(angle)

CHAPTER.color('#A51931')
CHAPTER.begin_fill()
CHAPTER.forward(length*9)
CHAPTER.left(angle)
CHAPTER.forward(length*1)
CHAPTER.left(angle)
CHAPTER.forward(length*9)
CHAPTER.left(angle)
CHAPTER.forward(length*1)
CHAPTER.left(angle)
CHAPTER.end_fill()

CHAPTER.right(angle)
CHAPTER.backward(length)
CHAPTER.left(angle)
CHAPTER.pendown()
CHAPTER.pensize(10)
CHAPTER.right(90)
CHAPTER.pencolor('black')
CHAPTER.pensize(10)
CHAPTER.forward(length*6+100)
CHAPTER.hideturtle()



turtle.exitonclick()