import turtle
jedi=turtle.Turtle()
jedi.speed(50)
turtle.bgcolor("grey")

jedi.color("purple","blue")
jedi.begin_fill()

jedi.penup()
jedi.pendown()

jedi.circle(300,45)
jedi.circle(50)
jedi.begin_fill()
jedi.circle(300,45)
jedi.circle(50)
jedi.end_fill()

jedi.color("purple","blue")
jedi.circle(300,45)
jedi.circle(50)
jedi.begin_fill()
jedi.circle(300,45)
jedi.circle(50)
jedi.end_fill()

jedi.color("purple","blue")
jedi.circle(300,45)
jedi.circle(50)
jedi.begin_fill()
jedi.circle(300,45)
jedi.circle(50)
jedi.end_fill()

jedi.color("purple","blue")
jedi.circle(300,45)
jedi.circle(50)
jedi.begin_fill()
jedi.circle(300,45)
jedi.circle(50)
jedi.end_fill()

jedi.color("purple","blue")
jedi.circle(300,45)
jedi.circle(50)
jedi.begin_fill()
jedi.circle(300,45)
jedi.circle(50)
jedi.end_fill()

jedi.color("purple","blue")
jedi.circle(300,45)
jedi.circle(50)
jedi.begin_fill()
jedi.circle(300,45)
jedi.circle(50)
jedi.end_fill()

jedi.color("purple","blue")
jedi.circle(300,45)
jedi.circle(50)
jedi.begin_fill()
jedi.circle(300,45)
jedi.circle(50)
jedi.end_fill()

jedi.color("purple","blue")
jedi.circle(300,45)
jedi.circle(50)
jedi.penup()
jedi.home()
jedi.goto(0,0)
jedi.pendown()

jedi.color("purple","blue")
jedi.begin_fill()
jedi.shape("square")
jedi.end_fill()

turtle.exitonclick()