import turtle
meen=turtle.Turtle()
meen.speed(3)
turtle.bgcolor("snow3")

meen.penup()
meen.back(800)
meen.pendown()

def triangle():
	meen.color("orange")
	meen.begin_fill()
	meen.forward(100)
	meen.left(120)
	meen.forward(100)
	meen.left(120)	
	meen.forward(100)
	meen.left(120)
	meen.forward(100)

triangle()
meen.forward(50)
triangle()
meen.forward(50)
triangle()
meen.forward(50)
triangle()
meen.forward(50)
triangle()
meen.forward(50)
triangle()
meen.forward(50)
triangle()
meen.forward(50)
triangle()
meen.forward(50)
triangle()
meen.forward(50)
triangle()
meen.forward(50)

turtle.exitonclick()