import turtle
nahmoun =turtle.Turtle()		
nahmoun.shape("turtle")
nahmoun.shapesize(2)
nahmoun.pensize(2)
screen=turtle.Screen()
screen.setup(2000,1800,0,0)
turtle	.bgcolor('pink')
nahmoun.forward(300)
nahmoun.left(120)
nahmoun.forward(300)
nahmoun.left(120)
nahmoun.forward(300)
nahmoun.forward	(300)
nahmoun.left(90)	
nahmoun.forward(300)	
nahmoun.left(90)	
nahmoun.forward(300)
nahmoun	.left(90)
nahmoun	.forward(300)			
nahmoun.left(90)																																																																																																																																																																					
turtle.exitonclick()
