import turtle
c=turtle.Turtle()
radius = 5
c.speed(0)

c.fillcolor('red')
c.begin_fill()
c.circle(radius + 80)
c.end_fill()
c.fillcolor('blue')
c.begin_fill()
c.circle(radius + 75)
c.end_fill()
c.fillcolor('green')
c.begin_fill()
c.circle(radius + 70)
c.end_fill()
c.fillcolor('red')
c.begin_fill()
c.circle(radius + 65)
c.end_fill()
c.fillcolor('blue')
c.begin_fill()
c.circle(radius + 60)
c.end_fill()
c.fillcolor('green')
c.begin_fill()
c.circle(radius + 55)
c.end_fill()
c.fillcolor('red')
c.begin_fill()
c.circle(radius + 50)
c.end_fill()
c.fillcolor('blue')
c.begin_fill()
c.circle(radius + 45)
c.end_fill()
c.fillcolor('green')
c.begin_fill()
c.circle(radius + 40)
c.end_fill()
c.fillcolor('red')
c.begin_fill()
c.circle(radius + 35)
c.end_fill()
c.fillcolor('blue')
c.begin_fill()
c.circle(radius + 30)
c.end_fill()
c.fillcolor('green')
c.begin_fill()
c.circle(radius + 25)
c.end_fill()
c.fillcolor('red')
c.begin_fill()
c.circle(radius + 20)
c.end_fill()
c.fillcolor('blue')
c.begin_fill()
c.circle(radius + 15)
c.end_fill()
c.fillcolor('green')
c.begin_fill()
c.circle(radius + 10)
c.end_fill()
c.fillcolor('red')
c.begin_fill()
c.circle(radius + 5)
c.end_fill()
c.fillcolor('blue')
c.begin_fill()
c.circle(radius)


c.circle(radius - 85)
c.end_fill()
c.fillcolor('red')
c.begin_fill()
c.circle(radius - 80)
c.end_fill()
c.fillcolor('blue')
c.begin_fill()
c.circle(radius - 75)
c.end_fill()
c.fillcolor('green')
c.begin_fill()
c.circle(radius - 70)
c.end_fill()
c.fillcolor('red')
c.begin_fill()
c.circle(radius - 65)
c.end_fill()
c.fillcolor('blue')
c.begin_fill()
c.circle(radius - 60)
c.end_fill()
c.fillcolor('green')
c.begin_fill()
c.circle(radius - 55)
c.end_fill()
c.fillcolor('red')
c.begin_fill()
c.circle(radius - 50)
c.end_fill()
c.fillcolor('blue')
c.begin_fill()
c.circle(radius - 45)
c.end_fill()
c.fillcolor('green')
c.begin_fill()
c.circle(radius - 40)
c.end_fill()
c.fillcolor('red')
c.begin_fill()
c.circle(radius - 35)
c.end_fill()
c.fillcolor('blue')
c.begin_fill()
c.circle(radius - 30)
c.end_fill()
c.fillcolor('green')
c.begin_fill()
c.circle(radius - 25)
c.end_fill()
c.fillcolor('red')
c.begin_fill()
c.circle(radius - 20)
c.end_fill()
c.fillcolor('blue')
c.begin_fill()
c.circle(radius - 15)
c.end_fill()
c.fillcolor('green')
c.begin_fill()
c.circle(radius - 10)
c.end_fill()
c.fillcolor('red')
c.begin_fill()
c.circle(radius - 5)
c.end_fill()
c.fillcolor('blue')
c.begin_fill()


turtle.exitonclick()